### PR TITLE
About Us screen added

### PR DESCRIPTION
**Pull request by SarinSthapit**
I would like to add more to the About Us screen and Settings screen if the committed changes are acceptable.

### CODE REVIEW

**Comment by Harishwarrior** [comment]
Can you also add open source license? You can check GPay about section for ideas.

**Comment by Harishwarrior** [comment]
Screenshot for reference

**Comment by SarinSthapit** [comment]
Please kindly review the committed changes.

**Comment by Harishwarrior** [comment]
Did you hard coded these values?

**Comment by SarinSthapit** [comment]
I had not changed the code for responsiveness. I have corrected that in this commit.

**Comment by Harishwarrior** [comment]
I think you don't understand the requirements here.

**Comment by Harishwarrior** [comment]
You should use this https://api.flutter.dev/flutter/material/LicensePage-class.html for license 


And get the current version of the app and show in about page.

We don't need terms of service or privacy policy.

**Comment by Harishwarrior** [comment]
> I had not changed the code for responsiveness. I have corrected that in this commit.

Revert the responsiveness commit.

**Comment by SarinSthapit** [comment]
Please let me know if any changes need to be made.

**Comment by Harishwarrior** [comment]
> > I had not changed the code for responsiveness. I have corrected that in this commit.
> 
> Revert the responsiveness commit.

@SarinSthapit

**Comment by SarinSthapit** [comment]
I have reverted the responsiveness commit and added the License Page. Please review it.

**Comment by Harishwarrior** [comment]
I'll review it tomorrow. Thanks.

**Comment by SarinSthapit** [comment]
Please review the most recent commit for hacktoberfest.

**Comment by Harishwarrior** [comment]
> Please review the most recent commit for hacktoberfest.

Screenshot?

**Comment by SarinSthapit** [comment]
This one is for Android platform while Cupertino toggle switch appears on iOS platform.

**Comment by Harishwarrior** [comment]
About page?

**Comment by SarinSthapit** [comment]
Just the toggle button beside the Dark mode

**Comment by Harishwarrior** [comment]
> Just the toggle button beside the Dark mode

Share screenshot of about page.

**Comment by SarinSthapit** [comment]
ntent.com/67547073/196044690-1a20ed1c-6a5a-4bfb-9815-8e541fa4aa07.jpg)

**Comment by Harishwarrior** [comment]
> 
> 
> ntent.com/67547073/196044690-1a20ed1c-6a5a-4bfb-9815-8e541fa4aa07.jpg)
> 


Why the app version is different?. It should the app version set on pubspec yaml

**Comment by Harishwarrior** [comment]
Sorry @SarinSthapit for the delay.

**Pull request merged**
